services:
  # Servicio de la aplicación Spring Boot
  app:
    build: .
    container_name: riwi-sprint-boot-app
    ports:
      - "8081:8080" # Mapea el puerto 8080 del contenedor al 8081 del host
    depends_on:
      - mysqldb
      - mongodb
    environment:
      # Configuración de conexión para MySQL
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/riwi_db?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      # Configuración de conexión para MongoDB
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/riwi_mongo_db
      # Configuración de JPA
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - riwi-network

  # Servicio de Base de Datos MySQL
  mysqldb:
    image: mysql:8.0
    container_name: riwi-mysql-db
    ports:
      - "3308:3306" # Mapea el puerto 3306 del contenedor al 3308 del host para evitar conflictos si tienes MySQL local
    environment:
      MYSQL_DATABASE: riwi_db
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - riwi-network

  # Servicio de Base de Datos MongoDB
  mongodb:
    image: mongo:latest
    container_name: riwi-mongo-db
    ports:
      - "27018:27017" # Mapea el puerto 27017 del contenedor al 27018 del host
    volumes:
      - mongo_data:/data/db
    networks:
      - riwi-network

# Definición de redes para que los contenedores se comuniquen entre sí
networks:
  riwi-network:
    driver: bridge

# Definición de volúmenes para persistencia de datos
volumes:
  mysql_data:
  mongo_data:
