spring.application.name=catalogos

# ======================================
# ===========  MYSQL CONFIG  ===========
# ======================================
spring.datasource.url=jdbc:mysql://localhost/db_hexagonal
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# --- JPA / Hibernate ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# ======================================
# =========   MONGO CONFIG  ============
# ======================================
# Usando BD separada para USERS
spring.data.mongodb.uri=mongodb://localhost:27017/catalogos_users

# Opcional:
# spring.data.mongodb.database=catalogos_users
