spring.application.name=catalogos
server.port=8080

# ======================================
# ===========  MYSQL CONFIG  ===========
# ======================================
spring.datasource.url=jdbc:mysql://127.0.0.1:3308/db_users_hexagonal
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# --- JPA / Hibernate ---
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# --- Flyway ---
spring.flyway.enabled=true

# ======================================
# =========   MONGO CONFIG  ============
# ======================================
spring.data.mongodb.uri=mongodb://localhost:27018/db_venues_mongo
