spring.application.name=catalogos

# --- DATABASE CONFIGURATION ---
spring.datasource.url=jdbc:mysql://localhost/db_hexagonal
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# --- JPA / HIBERNATE ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
